language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: BTEWWQ0b4IZ9KG+SazZRKyfugkBHbqb5imn3eA5XXBGyM0fqFTmwCXU+8DPN7QZc6XpRGCFyslcQqj1JOih/t/inZWDN7xS1UkH4t9eXMdkiUrF/SwvoFiEWKHs/zDH/lYo3huiOa69HRdV8DsXKkppd61Fi+VMQt47p0kGCvrYXBQHx+984CqjClwiUCJqMB7OTasLukwrqMx246hVhyGAkQWu5gLyQOscA+weR+/qP7gzJuDWg4A/GScRmxCItWDthqHDGZ0KQyeBS3jMxPAVOULum2O4AGGy9N4lC9CKvFGQxroWLuEVFKdugqd8Hn7UVDXar6UpAPd5qwHCzC1ehWt7X3eBMNGVUXgxA8/cwVAOePObNXIlzQ8+UU3lAXIz57hzsHG7bQ0nCDmf/qeUXtB6tSw3y9ZsiUvkLWLkEiF4PtG/IAtrSm2CMtkzh5FhJRELYfRw9NvTZl2YWzYHrVG9RtK/pF1G6wWDdCpo0KhQzPppuX2ymagbwuPEiHZPemriTv/sA27a1e155vmxqgSyXzUDn89PJEoFKhMEYqsjtaihlBXajU3Di71UvHl0n/EXUQ2Dz05MuCNuF3q1/R2KO6rRFp4ZW+L7nOhHxxtSQdHu0nce5k9SmOkcdaSSmobbfP0pL2NaIMi4hpkSD8fER+BjZnHf0R5Vdi0U=
  app: hidden-sea-75061
  on:
    repo: TmothyMartel/scenic
